<a href="https://colab.research.google.com/github/uavinash15/DataScience-/blob/main/Notebooks/NLP/Word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 41.5 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
from gensim.models import Word2Vec
import gensim.downloader
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import re
import spacy
nlp=spacy.load('en_core_web_sm')
import nltk
nltk.download('all')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_rus.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/bllip_wsj_no_aux.zip.
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/book_grammars.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/chat80.zip.
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/city_database.zip.
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/comparative_sentences.zip.
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2000.zip.
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2002.zip.
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/crubadan.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dependency_treebank.zip.
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dolch.zip.
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/english_wordnet.zip.
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/europarl_raw.zip.
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/floresta.zip.
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v15.zip.
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v17.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ieer.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/indian.zip.
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/kimmo.zip.
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/large_grammars.zip.
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/lin_thesaurus.zip.
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mac_morpho.zip.
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker_tab.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/maxent_treebank_pos_tagger.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/maxent_treebank_pos_tagger_tab.zip.
[nltk_data]    | Downloading package mock_corpus to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mock_corpus.zip.
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/moses_sample.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mte_teip5.zip.
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Unzipping misc/mwa_ppdb.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nonbreaking_prefixes.zip.
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nps_chat.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/opinion_lexicon.zip.
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/paradigms.zip.
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pe08.zip.
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping misc/perluniprops.zip.
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pil.zip.
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pl196x.zip.
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/porter_test.zip.
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ppattach.zip.
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/problem_reports.zip.
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_1.zip.
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_2.zip.
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pros_cons.zip.
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ptb.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package punkt_tab to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt_tab.zip.
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/qc.zip.
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/rslp.zip.
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/rte.zip.
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/sample_grammars.zip.
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/senseval.zip.
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentence_polarity.zip.
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentiwordnet.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sinica_treebank.zip.
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/smultron.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/spanish_grammars.zip.
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/state_union.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/subjectivity.zip.
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/swadesh.zip.
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/switchboard.zip.
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets.zip.
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets_json.zip.
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/timit.zip.
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/toolbox.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr.zip.
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr2.zip.
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/unicode_samples.zip.
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/universal_tagset.zip.
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet.zip.
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet3.zip.
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/webtext.zip.
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Unzipping models/wmt15_eval.zip.
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/word2vec_sample.zip.
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2022 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet2022.zip.
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ycoe.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection all

In [ ]:
df=pd.read_csv('netfilx_datasets.csv')

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
def data_clean(data):
  text=' '.join(re.findall('\w+',data))
  doc= nlp(text)
  cleaned_text= [token.lemma_ for token in doc if not token.is_stop and not token.is_punct
                 and not token.is_digit and not token.is_bracket and not token.is_currency]
  return cleaned_text

In [ ]:
df1=df.description
df1

0       As her father nears the end of his life, filmm...
1       After crossing paths at a party, a Cape Town t...
2       To protect his family from a powerful drug lor...
3       Feuds, flirtations and toilet talk go down amo...
4       In a city of coaching centers known to train I...
                              ...
8802    A political cartoonist, a crime reporter and a...
8803    While living alone in a spooky town, a young g...
8804    Looking to survive in a world taken over by zo...
8805    Dragged from civilian life, a former superhero...
8806    A scrappy but poor boy worms his way into a ty...
Name: description, Length: 8807, dtype: object

In [ ]:
df2=df1.apply(lambda x: data_clean(x))

In [ ]:
df2.head()

0    [father, near, end, life, filmmaker, Kirsten, ...
1    [cross, path, party, Cape, Town, teen, set, pr...
2    [protect, family, powerful, drug, lord, skille...
3    [Feuds, flirtation, toilet, talk, incarcerated...
4    [city, coaching, center, know, train, India, s...
Name: description, dtype: object

In [ ]:
data=[j for i in df2 for j in i]
print(data)

['father', 'near', 'end', 'life', 'filmmaker', 'Kirsten', 'Johnson', 'stag', 'death', 'inventive', 'comical', 'way', 'help', 'face', 'inevitable', 'cross', 'path', 'party', 'Cape', 'Town', 'teen', 'set', 'prove', 'private', 'school', 'swimming', 'star', 'sister', 'abduct', 'birth', 'protect', 'family', 'powerful', 'drug', 'lord', 'skilled', 'thief', 'Mehdi', 'expert', 'team', 'robber', 'pull', 'violent', 'deadly', 'turf', 'war', 'Feuds', 'flirtation', 'toilet', 'talk', 'incarcerated', 'woman', 'Orleans', 'Justice', 'Center', 'New', 'Orleans', 'gritty', 'reality', 'series', 'city', 'coaching', 'center', 'know', 'train', 'India', 's', 'fine', 'collegiate', 'mind', 'earnest', 'unexceptional', 'student', 'friend', 'navigate', 'campus', 'life', 'arrival', 'charismatic', 'young', 'priest', 'bring', 'glorious', 'miracle', 'ominous', 'mystery', 'renew', 'religious', 'fervor', 'die', 'town', 'desperate', 'believe', 'Equestria', 's', 'divide', 'bright', 'eyed', 'hero', 'believe', 'Earth', 'Ponies', 'Pegasi', 'Unicorns', 'pal', 'hoof', 'heart', 's', 'determined', 'prove', 'photo', 'shoot', 'Ghana', 'american', 'model', 'slip', 'time', 'enslave', 'plantation', 'bear', 'witness', 'agony', 'ancestral', 'past', 'talented', 'batch', 'amateur', 'baker', 'face', 'week', 'competition', 'whip', 'good', 'dish', 'hope', 'name', 'U', 'K', 's', 'good', 'woman', 'adjust', 'life', 'loss', 'contend', 'feisty', 'bird', 's', 'take', 'garden', 'husband', 's', 'struggle', 'find', 'way', 'forward', 'Sicily', 'boast', 'bold', 'Anti', 'Mafia', 'coalition', 'happen', 'try', 'bring', 'organize', 'crime', 'accuse', 'criminal', 'struggle', 'earn', 'living', 'Bangkok', 'man', 'join', 'emergency', 'rescue', 'service', 'realize', 'unravel', 'citywide', 'conspiracy', 'family', 'murder', 'terrorist', 'bombing', 'young', 'woman', 'unknowingly', 'lure', 'join', 'group', 'kill', 'clever', 'socially', 'awkward', 'Tetê', 'join', 'new', 'school', 'll', 'fit', 'queen', 'bee', 'classmate', 'idea', 'camera', 'follow', 'Bengaluru', 'police', 'job', 'offer', 'rare', 'glimpse', 'complex', 'challenging', 'inner', 'working', 'major', 'crime', 'investigation', 'student', 'color', 'navigate', 'daily', 'slight', 'slippery', 'politic', 'life', 'Ivy', 'League', 'college', 's', 'nearly', 'post', 'racial', 'think', 'declassify', 'document', 'reveal', 'post', 'WWII', 'life', 'Otto', 'Skorzeny', 'close', 'Hitler', 'ally', 'escape', 'Spain', 'adviser', 'world', 'president', 'Strangers', 'Diego', 'Isabel', 'flee', 'home', 'Mexico', 'pretend', 'married', 'couple', 'escape', 'drug', 'deal', 'enemy', 'abusive', 'husband', 'deadly', 'home', 'invasion', 'couple', 's', 'new', 'dream', 'house', 'traumatize', 'wife', 'search', 'answer', 'learn', 'real', 'danger', 'begin', '1960', 'Holocaust', 'survivor', 'join', 'group', 'self', 'train', 'spy', 'seek', 'justice', 'Nazis', 'flee', 'Spain', 'hide', 'WWII', 'late', '1970', 'accuse', 'serial', 'rapist', 'claim', 'multiple', 'personality', 'control', 'behavior', 'set', 'legal', 'odyssey', 'captivate', 'America', 'good', 'deed', 'unwittingly', 'endanger', 'clan', '13th', 'century', 'turkish', 'warrior', 'agree', 'fight', 'sultan', 's', 'enemy', 'exchange', 'new', 'tribal', 'land', 'newly', 'divorce', 'deny', 'visitation', 'right', 'daughter', 'doting', 'father', 'disguise', 'gray', 'haired', 'nanny', 'order', 'spend', 'time', 'arcade', 'game', 'sle', 'day', 'hiccup', 'cure', 'Cory', 'Carson', 's', 'curious', 'little', 'sister', 'Chrissy', 'speed', 'fun', 'adventure', 'town', 'father', 'man', 'love', 'insist', 'twin', 'son', 'marry', 'twin', 'sister', 'woman', 'create', 'alter', 'ego', 'bit', 'convincing', 'find', 'love', 'hard', 'young', 'adult', 'autism', 'spectrum', 'explore', 'unpredictable', 'world', 'date', 'complicated', 'tangled', 'love', 'triangle', 'ensue', 'man', 'fall', 'woman', 'study', 'nun', 'fall', 'friend', 'enlist', 'help', 'pursue', 'mourn', 'loss', 'beloved', 'junior', 'high', 'basketball', 'coach', 'middle', 'aged', 'pal', 'reunite', 'lake', 'house', 'rediscover', 'joy', 'kid', 'family', 's', 'idyllic', 'suburban', 'life', 'shatter', 'alien', 'force', 'invade', 'home', 'struggle', 'convince', 'deadly', 'threat', 'blackmail', 'company', 's', 'CEO', 'low', 'level', 'employee', 'find', 'force', 'spy', 'boss', 's', 'rival', 'mentor', 'big', 'city', 'life', 'buzz', 'lonely', 'soul', 'discover', 'surprising', 'source', 'connection', 'companionship', 'tale', 'love', 'loss', 'longing', 'Chicago', 'Party', 'Aunt', 'Diane', 'idolize', 'troublemaker', 'talent', 'avoid', 'adulthood', 'soft', 'spot', 'soul', 'search', 'nephew', 'insecure', 'Otis', 'answer', 'come', 'sex', 'advice', 'thank', 'therapist', 'mom', 'rebel', 'Maeve', 'propose', 'school', 'sex', 'therapy', 'clinic', 'hundred', 'cash', 'strap', 'player', 'accept', 'strange', 'invitation', 'compete', 'child', 's', 'game', 'inside', 'tempting', 'prize', 'await', 'deadly', 'high', 'stake', 'Tayo', 'speed', 'adventure', 'friend', 'kidnap', 'evil', 'magician', 'invade', 'city', 'search', 'magical', 'gemstone', 'son', 'go', 'missing', 'snowy', 'hike', 'mountain', 'retired', 'intelligence', 'officer', 'stop', 'risk', 'find', 'tired', 'small', 'time', 'grind', 'Marseille', 'cop', 'chance', 'bust', 'major', 'drug', 'network', 'line', 'blur', 'key', 'informant', 'make', 'big', 'ask', 'Birds', 'Red', 'Chuck', 'feather', 'friend', 'lot', 'adventure', 'guard', 'egg', 'nest', 'pesky', 'pig', 'try', 'steal', 'young', 'Bruce', 'Lee', 'anger', 'kung', 'fu', 'traditionalist', 'teach', 'outsider', 'lead', 'showdown', 'Shaolin', 'master', 'film', 'base', 'real', 'event', 'brave', 'energetic', 'little', 'boy', 'superhuman', 'power', 'lead', 'friend', 'exciting', 'adventure', 'guard', 'fellow', 'Dholakpur', 'villager', 'evil', 'mighty', 'teen', 'Adam', 'heroic', 'squad', 'misfit', 'discover', 'legendary', 'power', 'Grayskull', 'destiny', 'defend', 'Eternia', 'sinister', 'Skeletor', 'insatiable', 'great', 'white', 'shark', 'terrorize', 'Amity', 'Island', 'police', 'chief', 'oceanographer', 'grizzle', 'shark', 'hunter', 'seek', 'destroy', 'beast', 'year', 'deadly', 'shark', 'attack', 'police', 'chief', 'Martin', 'Brody', 'fight', 'protect', 'Amity', 'Island', 'killer', 'great', 'white', 'staff', 'marine', 'theme', 'park', 'try', 'capture', 'young', 'great', 'white', 'shark', 'discover', 'mother', 'invade', 'enclosure', 'blood', 'deadly', 'shark', 'attack', 'Ellen', 'Brody', 'Amity', 'Island', 'move', 'Caribbean', 'great', 'white', 'shark', 'follow', 'Robin', 'Wiltshire', 's', 'painful', 'childhood', 'rescue', 'Westerns', 'live', 'frontier', 'dream', 'train', 'horse', 'love', 'big', 'screen', 'young', 'CIA', 'operative', 'Matt', 'Weston', 'dangerous', 'criminal', 'agency', 'safe', 'house', 's', 'come', 'attack', 'securer', 'location', 'glamorous', 'millennial', 'strive', 'success', 'juggle', 'career', 'finance', 'love', 'friendship', 'base', 'Arese', 'Ugwu', 's', 'good', 'selling', 'novel', 'rookie', 'cop', 'day', 'prove', 'veteran', 'lapd', 'narcotic', 'officer', 'receive', 'crash', 'course', 'mentor', 's', 'questionable', 'brand', 'justice', 'pair', 'high', 'power', 'successful', 'lawyer', 'find', 'defend', 'opposite', 'interest', 'justice', 'system', 'cause', 'strain', 'happy', 'marriage', 'ancient', 'Great', 'War', 'god', 'Chitragupta', 'oversee', 'trial', 'determine', 'battle', 's', 'true', 'hero', 'villain', 'big', 'foe', 'seemingly', 'defeat', 'InuYasha', 'friend', 'return', 'everyday', 'life', 'peace', 'soon', 'shatter', 'emerge', 'new', 'enemy', 'Great', 'Dog', 'Demon', 'beaqueathe', 'Swords', 'Fang', 'son', 'evil', 'power', 'sword', 'awaken', 'ai', 'young', 'half', 'demon', 'escape', 'Horai', 'Island', 'try', 'help', 'people', 'return', 'potential', 'savior', 'InuYasha', 'Sesshomaru', 'Kikyo', 'powerful', 'demon', 'seal', 'away', 'year', 'demon', 's', 'son', 'awaken', 'fate', 'world', 'jeopardy', 'home', 'baker', 'terrible', 'track', 'record', 'crack', 'create', 'edible', 'masterpiece', 'prize', 's', 'reality', 'contest', 'hot', 'mess', 'mistakenly', 'accuse', 'attack', 'Fourth', 'Raikage', 'ninja', 'Naruto', 'imprison', 'impenetrable', 'Hozuki', 'Castle', 'power', 'seal', 'strange', 'ninjas', 'ambush', 'village', 'Konohagakure', 's', 'adolescent', 'ninja', 'Naruto', 'long', 'miss', 'pal', 'Sasuke', 'save', 'planet', 'ninja', 'village', 'destroy', 'leader', 'spar', 'try', 'find', 'true', 'culprit', 'protect', 'land', 'adventure', 'adolescent', 'ninja', 'Naruto', 'Uzumaki', 'continue', 's', 'tasked', 'protect', 'priestess', 'demon', 'die', 'Naruto', 'send', 'recover', 'miss', 'nin', 'rogue', 'manage', 'send', 'year', 'past', 'unite', 'father', 'battle', 'evil', 'mission', 'return', 'missing', 'pet', 'Naruto', 'fellow', 'ninjas', 'ambush', 'brutal', 'knight', 'lead', 'enigmatic', 'Temujin', 'exuberant', 'ninja', 'Naruto', 'team', 'pal', 'Sakura', 'Kakashi', 'escort', 'Prince', 'Michiru', 'son', 'Hikaru', 'Crescent', 'Moon', 'kingdom', 'Naruto', 'Sasuke', 'Sakura', 'learn', 'll', 'protect', 'actress', 'hurt', 'make', 'film', 'turn', 's', 'princess', 'scary', 'story', 'fan', 'Alex', 'tell', 'spine', 'tingle', 'tale', 'night', 'stay', 'trap', 'new', 'friend', 'wicked', 'witch', 's', 'magical', 'apartment', 'forever', 'place', 'call', 'Numberland', 'math', 'add', 'ton', 'fun', 'group', 'cheerful', 'block', 'work', 'play', 'sing', 'explore', 'history', 'flavor', 'regional', 'indian', 'cuisine', 'traditional', 'Kashmiri', 'feast', 'vegetarian', 'dish', 'gujarat', 'middle', 'school', 'college', 'good', 'friend', 'Zack', 'Kelly', 'Slater', 'Jessie', 'Screech', 'Lisa', 'high', 'low', 'life', 'hit', 'series', 'exclusive', 'interview', 'archival', 'footage', 'documentary', 'trace', 'intimate', 'portrait', 'seven', 'time', 'Formula', 'champion', 'Michael', 'Schumacher', 'writing', 'Nobel', 'Prize', 'winner', 'Rabindranath', 'Tagore', 'come', 'life', 'collection', 'tale', 'set', 'early', '20th', 'century', 'bengal', 'reality', 'single', 'Latin', 'America', 'Spain', 'challenge', 'sex', 'abstinence', 'come', 'silver', 'line', 'join', 'StoryBots', 'space', 'traveler', 'historic', 'inspiration4', 'mission', 'search', 'answer', 'kid', 'question', 'space', 'jovial', 'comic', 'Jack', 'Whitehall', 'invite', 'stuffy', 'father', 'Michael', 'travel', 'Southeast', 'Asia', 'attempt', 'strengthen', 'bond', 'powerful', 'businesswoman', 's', 'political', 'ambition', 'threaten', 'underworld', 'connection', 'ensue', 'power', 'struggle', 'cost', 'eye', 'budget', 'traveler', 'visit', 'vacation', 'rental', 'globe', 'share', 'expert', 'tip', 'trick', 'reality', 'series', 'plane', 'crash', 'leave', 'Bear', 'amnesia', 'choice', 'save', 'miss', 'pilot', 'survive', 'high', 'stake', 'interactive', 'adventure', 'timid', 'anime', 'love', 'teen', 'get', 'draw', 'school', 'cycling', 'club', 'new', 'friend', 'help', 'face', 'tough', 'challenge', 'develop', 'racing', 'talent', 'kid', 'cop', 'Little', 'Singham', 'lose', 'superpower', 'try', 'stop', 'demon', 'Kaal', 's', 'new', 'evil', 'plan', 'inner', 'strength', 'help', 'defeat', 'enemy', 'bud', 'politician', 'devious', 'plan', 'rise', 'rank', 'unexpected', 'new', 'presence', 'begin', 'interfere', 'crooked', 'bud', 'politician', 'devious', 'plan', 'rise', 'rank', 'unexpected', 'new', 'presence', 'begin', 'interfere', 'crooked', 'home', 'threaten', 'human', 'young', 'dragon', 'summon', 'courage', 'seek', 'mythical', 'paradise', 'dragon', 'live', 'peace', 'fly', 'free', 'slip', 'fatal', 'poison', 'final', 'job', 'ruthless', 'assassin', 'work', 'Tokyo', 'hour', 'find', 'order', 'hit', 'exact', 'revenge', 'bore', 'Lord', 'Hell', 'devil', 'relocate', 'Los', 'Angeles', 'open', 'nightclub', 'form', 'connection', 'homicide', 'detective', 'competition', 'group', 'metal', 'artist', 'torch', 'cut', 'weld', 'epic', 'badass', 'creation', 'hardened', 'steel', 'win', 'prize', 'twin', 'reunite', 'good', 'hearted', 'female', 'gangster', 'uptight', 'rich', 'sister', 'family', 'crime', 'cop', 'trouble', 'follow', 'Ash', 'battle', 'way', 'World', 'Coronation', 'Series', 'Goh', 'continue', 'quest', 'catch', 'Pokémon', 'journey', 'adventure', 'hiking', 'trip', 'wild', 'turn', 'desperate', 'bid', 'survival', 'friend', 'run', 'mysterious', 'shooter', 'titipo', 'train', 'prove', 's', 'get', 'take', 'help', 'folk', 'Train', 'Village', 'ride', 'rail', 'safely', 'reliably', 'chance', 'meeting', 'tragic', 'fallout', 'Malcolm', 'X', 'Muhammad', 'Ali', 's', 'extraordinary', 'bond', 'crack', 'weight', 'distrust', 'shift', 'ideal', 'bear', 'superhuman', 'ability', 'young', 'Raju', 'want', 'use', 'power', 'world', 'well', 'place', 'mean', 'face', 'plenty', 'challenge', 'Uma', 'wake', 'lush', 'tropical', 'facility', 'design', 'turn', 'willful', 'girl', 'perfect', 'lady', 's', 'bad', 'real', 'purpose', 'bad', 'documentary', 'trace', 'capture', 'serial', 'killer', 'Guy', 'Georges', 'tireless', 'work', 'woman', 'police', 'chief', 'victim', 's', 'mother', 'passenger', 'crew', 'aboard', 'hijacked', 'overnight', 'flight', 'scramble', 'outrace', 'sun', 'mysterious', 'cosmic', 'event', 'wreak', 'havoc', 'world', 'Elisabeth', 'John', 'John', 'live', 'city', 'inhabit', 'different', 'world', 'passionate', 'love', 'break', 'class', 'cultural', 'barrier', 'rough', 'tough', 'police', 'dog', 'undercover', 'FBI', 'agent', 'prim', 'proper', 'pet', 'dog', 'save', 'baby', 'panda', 'illegal', 'sale', 'status', 'strategy', 'collide', 'social', 'experiment', 'competition', 'online', 'player', 'flirt', 'befriend', 'catfish', 'way', 'interview', 'archival', 'footage', 'documentary', 'chart', 'story', 'legendary', 'Southern', 'rocker', 'focus', 'man', 'Ronnie', 'Van', 'Zant', 'boy', 's', 'superhero', 'dream', 'come', 'true', 'find', 'powerful', 'cosmic', 'stone', 'save', 'day', 'hard', 'imagine', 't', 'Octonauts', 'expand', 'exploration', 'sea', 'land', 'new', 'ride', 'new', 'friend', 'll', 'protect', 'habitat', 'animal', 'risk', 'woman', 'chef', 'single', 'mom', 'heiress', 'job', 'seeker', 'dig', 'love', 'work', 'generous', 'midlife', 'crisis', 'pre', 'pandemic', 'LA', 'intergalactic', 'device', 'transform', 'toy', 'car', 'robot', 'Tobots', 'work', 'friend', 'solve', 'mystery', 'protect', 'world', 'evil', 'pressure', 'continue', 'win', 'tradition', 'american', 'tennis', 'mardy', 'fish', 'face', 'mental', 'health', 'challenge', 'change', 'life', 'court', 'training', 'launch', 'land', 'access', 'docuserie', 'rid', 'inspiration4', 'crew', 'civilian', 'orbital', 'space', 'mission', 'family', 'face', 'destruction', 'long', 'run', 'conflict', 'community', 'pit', 'relative', 'amid', 'attack', 'reprisal', 'learn', 'route', 'busy', 'city', 'Tayo', 'little', 'bus', 'friend', 'discover', 'new', 'sight', 'exciting', 'adventure', 'day', 'grow', 'amidst', 'gang', 'war', 'hometown', 'Vincent', 'form', 'entrepreneurial', 'squad', 'end', 'wrong', 'law', 'Ross', 'sibling', 'Disney', 's', 'hit', 'series', 'Jessie', 'spend', 'summer', 'fun', 'adventure', 'Maine', 's', 'Camp', 'Kikiwaka', 'parent', 'meet', 'grieve', 'teen', 'work', 'debt', 'ranch', 'care', 'wound', 'horse', 'teach', 'healing', 'expect', 'shore', 'Cape', 'Mercy', 'skillful', 'group', 'teen', 'diver', 'investigate', 'series', 'secret', 'sign', 'mysteriously', 'go', 'missing', 'thief', 'hostage', 'lock', 'Royal', 'Mint', 'Spain', 'criminal', 'mastermind', 'manipulate', 'police', 'carry', 'plan', 'filmmaker', 'actor', 'Money', 'heist', 'character', 'like', 'Tokyo', 'Professor', 'talk', 'emotional', 'artistic', 'process', 'film', 'series', 'half', 'shark', 'half', 'dog', 'big', 'heart', 'belly', 'fish', 'stick', 'Sharkdog', 'human', 'pal', 'Max', 'silly', 'messy', 'adventure', 'wake', 'Sept', 'attack', 'lawyer', 'face', 'emotional', 'reckoning', 'attempt', 'dollar', 'value', 'life', 'lose', 'base', 'real', 'event', 'cassie', 'live', 'party', 'die', 'freak', 'accident', 'social', 'butterfly', 'need', 'right', 'wrong', 'Earth', 'want', 'earn', 'wing', 'wealthy', 'industrialist', 's', 'dangerous', 'obsession', 'flight', 'attendant', 'destroy', 'world', 'take', 'matter', 'hand', 'exact', 'revenge', 'drama', 'detail', 'passionate', 'year', 'romance', 'romantic', 'poet', 'John', 'Keats', 'die', 'tragically', 'age', 'great', 'love', 'muse', 'movie', 'love', 'year', 'old', 'blind', 'little', 'brother', 'trek', 'meet', 'indian', 'superstar', 'Shah', 'Rukh', 'Khan', 'help', 'get', 'boy', 'eye', 'operation', 'documentary', 'stitch', 'see', 'interview', 'live', 'generation', 'people', 'participate', 'Hitler', 's', 'Reich', 'daughter', 'wealthy', 'family', 'return', 'college', 'get', 'frosty', 'welcome', 'brother', 'problem', 'plan', 'meet', 'heated', 'exchange', 'social', 'medium', 'people', 'different', 'background', 'begin', 'online', 'romance', 'midst', 'pandemic', 'meteor', 'crash', 'group', 'zoo', 'animal', 'transform', 'squishy', 'gooey', 'stretchy', 'superhero', 'special', 'power', 'soon', 'take', 'evildoer', 's', 'invite', 'manage', 'hotel', 'dead', 'soul', 'elite', 'hoteli', 'get', 'know', 'establishment', 's', 'ancient', 'owner', 'strange', 'world', 'embark', 'affair', 'cop', 'probe', 'murder', 'young', 'woman', 'insular', 'schoolteacher', 'suspect', 'lover', 'involve', 'crime', 'base', 'book', 'epic', 'Ramayana', 'series', 'follow', 'endeavor', 'adventure', 'Lord', 'Rama', 's', 'twin', 'son', 'childhood', 'tiny', 'island', 'Pororo', 'penguin', 'fun', 'adventure', 'friend', 'Eddy', 'fox', 'Loopy', 'beaver', 'Poby', 'polar', 'bear', 'Crong', 'dinosaur', 'gay', 'superspy', 'scrappy', 'LGBTQ', 'squad', 'fight', 'prove', 'agency', 'underestimate', 'today', 'West', 'Hollywood', 'tomorrow', 'world', 'couple', 'strive', 'remain', 'resilient', 'regional', 'hostility', 'drive', 'beloved', 'home', 'refugee', 'camp', 'Teen', 'Sam', 'meet', 'boy', 'dream', 'dance', 'return', 'toil', 'stepmother', 's', 'diner', 'lose', 'cell', 'phone', 'bring', 'detective', 'investigate', 'death', 'ex', 'lover', 's', 'grandfather', 'uncover', 'secret', 'tycoon', 's', 'manipulative', 'family', 'grieve', 'widow', 'daughter', 'estranged', 'father', 'law', 'Wyoming', 'time', 'allow', 'heal', 'forgive', 'summer', 'perform', 'art', 'program', 'New', 'York', 'City', 'Barbie', 'Malibu', 'meet', 'Barbie', 'Brooklyn', 'fast', 'friend', 'smog', 'choke', 'dystopian', 'Los', 'Angeles', 'blade', 'runner', 'Rick', 'Deckard', 'call', 'retirement', 'snuff', 'quartet', 'escape', 'replicant', 'group', 'superhero', 'set', 'rid', 'world', 'evil', 'realize', 'stand', 'justice', 'base', 'popular', 'comic', 'futuristic', 'society', 'indestructible', 'robot', 'police', 'force', 'keep', 'crime', 'bay', 'lone', 'droid', 'evolve', 'level', 'artificial', 'intelligence', 'president', 's', 'friend', 'murder', 'CIA', 'Deputy', 'Director', 'Jack', 'Ryan', 'unwittingly', 'involve', 'illegal', 'war', 'colombian', 'drug', 'cartel', 'Ranger', 'Gabe', 'Walker', 'partner', 'call', 'rescue', 'group', 'stranded', 'climber', 'learn', 'climber', 'actually', 'thieve', 'hijacker', 'drama', 'follow', 'wound', 'Civil', 'War', 'soldier', 'make', 'long', 'journey', 'home', 'faraway', 'love', 'fight', 'survival', 'deceased', 'father', 's', 'farm', 'Mick', 'Crocodile', 'Dundee', 'family', 'land', 'Los', 'Angeles', 'soon', 'learn', 'lesson', 'american', 'life', 'comedy', 'sequel', 'summer', 'leave', 'U', 'S', 'soldier', 'fall', 'college', 'student', 's', 'force', 'reenlist', 'handwritten', 'letter', 'hold', 'lover', 'sweltering', 'day', 'Brooklyn', 'simmer', 'racial', 'tension', 'resident', 'rise', 'surface', 'ignite', 'rage', 'violence', 'tragedy', 'lawyer', 'defend', 'illiterate', 'man', 'exploitation', 'cruel', 'boss', 'work', 'butcher', 'Buenos', 'Aires', 'lead', 'tragedy', 'base', 'true', 'case', 'retired', 'CIA', 'agent', 'kidnap', 'son', 'government', 'analyst', 'embark', 'unauthorized', 'mission', 'find', 'halt', 'terrorist', 'plot', 'risk', 'student', 'read', 'classic', 'Diary', 'Anne', 'Frank', 'teacher', 'ask', 'journal', 'troubled', 'life', 'test', 'pilot', 'Hal', 'Jordan', 'harness', 'glow', 'new', 'power', 'good', 'wear', 'otherworldly', 'ring', 'help', 'intergalactic', 'for

In [ ]:
len(data)

124559

In [ ]:
data1=[word_tokenize(x) for x in data]
print(data1)

[['father'], ['near'], ['end'], ['life'], ['filmmaker'], ['Kirsten'], ['Johnson'], ['stag'], ['death'], ['inventive'], ['comical'], ['way'], ['help'], ['face'], ['inevitable'], ['cross'], ['path'], ['party'], ['Cape'], ['Town'], ['teen'], ['set'], ['prove'], ['private'], ['school'], ['swimming'], ['star'], ['sister'], ['abduct'], ['birth'], ['protect'], ['family'], ['powerful'], ['drug'], ['lord'], ['skilled'], ['thief'], ['Mehdi'], ['expert'], ['team'], ['robber'], ['pull'], ['violent'], ['deadly'], ['turf'], ['war'], ['Feuds'], ['flirtation'], ['toilet'], ['talk'], ['incarcerated'], ['woman'], ['Orleans'], ['Justice'], ['Center'], ['New'], ['Orleans'], ['gritty'], ['reality'], ['series'], ['city'], ['coaching'], ['center'], ['know'], ['train'], ['India'], ['s'], ['fine'], ['collegiate'], ['mind'], ['earnest'], ['unexceptional'], ['student'], ['friend'], ['navigate'], ['campus'], ['life'], ['arrival'], ['charismatic'], ['young'], ['priest'], ['bring'], ['glorious'], ['miracle'], ['ominous'], ['mystery'], ['renew'], ['religious'], ['fervor'], ['die'], ['town'], ['desperate'], ['believe'], ['Equestria'], ['s'], ['divide'], ['bright'], ['eyed'], ['hero'], ['believe'], ['Earth'], ['Ponies'], ['Pegasi'], ['Unicorns'], ['pal'], ['hoof'], ['heart'], ['s'], ['determined'], ['prove'], ['photo'], ['shoot'], ['Ghana'], ['american'], ['model'], ['slip'], ['time'], ['enslave'], ['plantation'], ['bear'], ['witness'], ['agony'], ['ancestral'], ['past'], ['talented'], ['batch'], ['amateur'], ['baker'], ['face'], ['week'], ['competition'], ['whip'], ['good'], ['dish'], ['hope'], ['name'], ['U'], ['K'], ['s'], ['good'], ['woman'], ['adjust'], ['life'], ['loss'], ['contend'], ['feisty'], ['bird'], ['s'], ['take'], ['garden'], ['husband'], ['s'], ['struggle'], ['find'], ['way'], ['forward'], ['Sicily'], ['boast'], ['bold'], ['Anti'], ['Mafia'], ['coalition'], ['happen'], ['try'], ['bring'], ['organize'], ['crime'], ['accuse'], ['criminal'], ['struggle'], ['earn'], ['living'], ['Bangkok'], ['man'], ['join'], ['emergency'], ['rescue'], ['service'], ['realize'], ['unravel'], ['citywide'], ['conspiracy'], ['family'], ['murder'], ['terrorist'], ['bombing'], ['young'], ['woman'], ['unknowingly'], ['lure'], ['join'], ['group'], ['kill'], ['clever'], ['socially'], ['awkward'], ['Tetê'], ['join'], ['new'], ['school'], ['ll'], ['fit'], ['queen'], ['bee'], ['classmate'], ['idea'], ['camera'], ['follow'], ['Bengaluru'], ['police'], ['job'], ['offer'], ['rare'], ['glimpse'], ['complex'], ['challenging'], ['inner'], ['working'], ['major'], ['crime'], ['investigation'], ['student'], ['color'], ['navigate'], ['daily'], ['slight'], ['slippery'], ['politic'], ['life'], ['Ivy'], ['League'], ['college'], ['s'], ['nearly'], ['post'], ['racial'], ['think'], ['declassify'], ['document'], ['reveal'], ['post'], ['WWII'], ['life'], ['Otto'], ['Skorzeny'], ['close'], ['Hitler'], ['ally'], ['escape'], ['Spain'], ['adviser'], ['world'], ['president'], ['Strangers'], ['Diego'], ['Isabel'], ['flee'], ['home'], ['Mexico'], ['pretend'], ['married'], ['couple'], ['escape'], ['drug'], ['deal'], ['enemy'], ['abusive'], ['husband'], ['deadly'], ['home'], ['invasion'], ['couple'], ['s'], ['new'], ['dream'], ['house'], ['traumatize'], ['wife'], ['search'], ['answer'], ['learn'], ['real'], ['danger'], ['begin'], ['1960'], ['Holocaust'], ['survivor'], ['join'], ['group'], ['self'], ['train'], ['spy'], ['seek'], ['justice'], ['Nazis'], ['flee'], ['Spain'], ['hide'], ['WWII'], ['late'], ['1970'], ['accuse'], ['serial'], ['rapist'], ['claim'], ['multiple'], ['personality'], ['control'], ['behavior'], ['set'], ['legal'], ['odyssey'], ['captivate'], ['America'], ['good'], ['deed'], ['unwittingly'], ['endanger'], ['clan'], ['13th'], ['century'], ['turkish'], ['warrior'], ['agree'], ['fight'], ['sultan'], ['s'], ['enemy'], ['exchange'], ['new'], ['tribal'], ['land'], ['newly'], ['divorce'], ['deny'], ['visitation'], ['right'], ['daughter'], ['doting'], ['father'], ['disguise'], ['gray'], ['haired'], ['nanny'], ['order'], ['spend'], ['time'], ['arcade'], ['game'], ['sle'], ['day'], ['hiccup'], ['cure'], ['Cory'], ['Carson'], ['s'], ['curious'], ['little'], ['sister'], ['Chrissy'], ['speed'], ['fun'], ['adventure'], ['town'], ['father'], ['man'], ['love'], ['insist'], ['twin'], ['son'], ['marry'], ['twin'], ['sister'], ['woman'], ['create'], ['alter'], ['ego'], ['bit'], ['convincing'], ['find'], ['love'], ['hard'], ['young'], ['adult'], ['autism'], ['spectrum'], ['explore'], ['unpredictable'], ['world'], ['date'], ['complicated'], ['tangled'], ['love'], ['triangle'], ['ensue'], ['man'], ['fall'], ['woman'], ['study'], ['nun'], ['fall'], ['friend'], ['enlist'], ['help'], ['pursue'], ['mourn'], ['loss'], ['beloved'], ['junior'], ['high'], ['basketball'], ['coach'], ['middle'], ['aged'], ['pal'], ['reunite'], ['lake'], ['house'], ['rediscover'], ['joy'], ['kid'], ['family'], ['s'], ['idyllic'], ['suburban'], ['life'], ['shatter'], ['alien'], ['force'], ['invade'], ['home'], ['struggle'], ['convince'], ['deadly'], ['threat'], ['blackmail'], ['company'], ['s'], ['CEO'], ['low'], ['level'], ['employee'], ['find'], ['force'], ['spy'], ['boss'], ['s'], ['rival'], ['mentor'], ['big'], ['city'], ['life'], ['buzz'], ['lonely'], ['soul'], ['discover'], ['surprising'], ['source'], ['connection'], ['companionship'], ['tale'], ['love'], ['loss'], ['longing'], ['Chicago'], ['Party'], ['Aunt'], ['Diane'], ['idolize'], ['troublemaker'], ['talent'], ['avoid'], ['adulthood'], ['soft'], ['spot'], ['soul'], ['search'], ['nephew'], ['insecure'], ['Otis'], ['answer'], ['come'], ['sex'], ['advice'], ['thank'], ['therapist'], ['mom'], ['rebel'], ['Maeve'], ['propose'], ['school'], ['sex'], ['therapy'], ['clinic'], ['hundred'], ['cash'], ['strap'], ['player'], ['accept'], ['strange'], ['invitation'], ['compete'], ['child'], ['s'], ['game'], ['inside'], ['tempting'], ['prize'], ['await'], ['deadly'], ['high'], ['stake'], ['Tayo'], ['speed'], ['adventure'], ['friend'], ['kidnap'], ['evil'], ['magician'], ['invade'], ['city'], ['search'], ['magical'], ['gemstone'], ['son'], ['go'], ['missing'], ['snowy'], ['hike'], ['mountain'], ['retired'], ['intelligence'], ['officer'], ['stop'], ['risk'], ['find'], ['tired'], ['small'], ['time'], ['grind'], ['Marseille'], ['cop'], ['chance'], ['bust'], ['major'], ['drug'], ['network'], ['line'], ['blur'], ['key'], ['informant'], ['make'], ['big'], ['ask'], ['Birds'], ['Red'], ['Chuck'], ['feather'], ['friend'], ['lot'], ['adventure'], ['guard'], ['egg'], ['nest'], ['pesky'], ['pig'], ['try'], ['steal'], ['young'], ['Bruce'], ['Lee'], ['anger'], ['kung'], ['fu'], ['traditionalist'], ['teach'], ['outsider'], ['lead'], ['showdown'], ['Shaolin'], ['master'], ['film'], ['base'], ['real'], ['event'], ['brave'], ['energetic'], ['little'], ['boy'], ['superhuman'], ['power'], ['lead'], ['friend'], ['exciting'], ['adventure'], ['guard'], ['fellow'], ['Dholakpur'], ['villager'], ['evil'], ['mighty'], ['teen'], ['Adam'], ['heroic'], ['squad'], ['misfit'], ['discover'], ['legendary'], ['power'], ['Grayskull'], ['destiny'], ['defend'], ['Eternia'], ['sinister'], ['Skeletor'], ['insatiable'], ['great'], ['white'], ['shark'], ['terrorize'], ['Amity'], ['Island'], ['police'], ['chief'], ['oceanographer'], ['grizzle'], ['shark'], ['hunter'], ['seek'], ['destroy'], ['beast'], ['year'], ['deadly'], ['shark'], ['attack'], ['police'], ['chief'], ['Martin'], ['Brody'], ['fight'], ['protect'], ['Amity'], ['Island'], ['killer'], ['great'], ['white'], ['staff'], ['marine'], ['theme'], ['park'], ['try'], ['capture'], ['young'], ['great'], ['white'], ['shark'], ['discover'], ['mother'], ['invade'], ['enclosure'], ['blood'], ['deadly'], ['shark'], ['attack'], ['Ellen'], ['Brody'], ['Amity'], ['Island'], ['move'], ['Caribbean'], ['great'], ['white'], ['shark'], ['follow'], ['Robin'], ['Wiltshire'], ['s'], ['painful'], ['childhood'], ['rescue'], ['Westerns'], ['live'], ['frontier'], ['dream'], ['train'], ['horse'], ['love'], ['big'], ['screen'], ['young'], ['CIA'], ['operative'], ['Matt'], ['Weston'], ['dangerous'], ['criminal'], ['agency'], ['safe'], ['house'], ['s'], ['come'], ['attack'], ['securer'], ['location'], ['glamorous'], ['millennial'], ['strive'], ['success'], ['juggle'], ['career'], ['finance'], ['love'], ['friendship'], ['base'], ['Arese'], ['Ugwu'], ['s'], ['good'], ['selling'], ['novel'], ['rookie'], ['cop'], ['day'], ['prove'], ['veteran'], ['lapd'], ['narcotic'], ['officer'], ['receive'], ['crash'], ['course'], ['mentor'], ['s'], ['questionable'], ['brand'], ['justice'], ['pair'], ['high'], ['power'], ['successful'], ['lawyer'], ['find'], ['defend'], ['opposite'], ['interest'], ['justice'], ['system'], ['cause'], ['strain'], ['happy'], ['marriage'], ['ancient'], ['Great'], ['War'], ['god'], ['Chitragupta'], ['oversee'], ['trial'], ['determine'], ['battle'], ['s'], ['true'], ['hero'], ['villain'], ['big'], ['foe'], ['seemingly'], ['defeat'], ['InuYasha'], ['friend'], ['return'], ['everyday'], ['life'], ['peace'], ['soon'], ['shatter'], ['emerge'], ['new'], ['enemy'], ['Great'], ['Dog'], ['Demon'], ['beaqueathe'], ['Swords'], ['Fang'], ['son'], ['evil'], ['power'], ['sword'], ['awaken'], ['ai'], ['young'], ['half'], ['demon'], ['escape'], ['Horai'], ['Island'], ['try'], ['help'], ['people'], ['return'], ['potential'], ['savior'], ['InuYasha'], ['Sesshomaru'], ['Kikyo'], ['powerful'], ['demon'], ['seal'], ['away'], ['year'], ['demon'], ['s'], ['son'], ['awaken'], ['fate'], ['world'], ['jeopardy'], ['home'], ['baker'], ['terrible'], ['track'], ['record'], ['crack'], ['create'], ['edible'], ['masterpiece'], ['prize'], ['s'], ['reality'], ['contest'], ['hot'], ['mess'], ['mistakenly'], ['accuse'], ['attack'], ['Fourth'], ['Raikage'], ['ninja'], ['Naruto'], ['imprison'], ['impenetrable'], ['Hozuki'], ['Castle'], ['power'], ['seal'], ['strange'], ['ninjas'], ['ambush'], ['village'], ['Konohagakure'], ['s'], ['adolescent'], ['ninja'], ['Naruto'], ['long'], ['miss'], ['pal'], ['Sasuke'], ['save'], ['planet'], ['ninja'], ['village'], ['destroy'], ['leader'], ['spar'], ['try'], ['find'], ['true'], ['culprit'], ['protect'], ['land'], ['adventure'], ['adolescent'], ['ninja'], ['Naruto'], ['Uzumaki'], ['continue'], ['s'], ['tasked'], ['protect'], ['priestess'], ['demon'], ['die'], ['Naruto'], ['send'], ['recover'], ['miss'], ['nin'], ['rogue'], ['manage'], ['send'], ['year'], ['past'], ['unite'], ['father'], ['battle'], ['evil'], ['mission'], ['return'], ['missing'], ['pet'], ['Naruto'], ['fellow'], ['ninjas'], ['ambush'], ['brutal'], ['knight'], ['lead'], ['enigmatic'], ['Temujin'], ['exuberant'], ['ninja'], ['Naruto'], ['team'], ['pal'], ['Sakura'], ['Kakashi'], ['escort'], ['Prince'], ['Michiru'], ['son'], ['Hikaru'], ['Crescent'], ['Moon'], ['kingdom'], ['Naruto'], ['Sasuke'], ['Sakura'], ['learn'], ['ll'], ['protect'], ['actress'], ['hurt'], ['make'], ['film'], ['turn'], ['s'], ['princess'], ['scary'], ['story'], ['fan'], ['Alex'], ['tell'], ['spine'], ['tingle'], ['tale'], ['night'], ['stay'], ['trap'], ['new'], ['friend'], ['wicked'], ['witch'], ['s'], ['magical'], ['apartment'], ['forever'], ['place'], ['call'], ['Numberland'], ['math'], ['add'], ['ton'], ['fun'], ['group'], ['cheerful'], ['block'], ['work'], ['play'], ['sing'], ['explore'], ['history'], ['flavor'], ['regional'], ['indian'], ['cuisine'], ['traditional'], ['Kashmiri'], ['feast'], ['vegetarian'], ['dish'], ['gujarat'], ['middle'], ['school'], ['college'], ['good'], ['friend'], ['Zack'], ['Kelly'], ['Slater'], ['Jessie'], ['Screech'], ['Lisa'], ['high'], ['low'], ['life'], ['hit'], ['series'], ['exclusive'], ['interview'], ['archival'], ['footage'], ['documentary'], ['trace'], ['intimate'], ['portrait'], ['seven'], ['time'], ['Formula'], ['champion'], ['Michael'], ['Schumacher'], ['writing'], ['Nobel'], ['Prize'], ['winner'], ['Rabindranath'], ['Tagore'], ['come'], ['life'], ['collection'], ['tale'], ['set'], ['early'], ['20th'], ['century'], ['bengal'], ['reality'], ['single'], ['Latin'], ['America'], ['Spain'], ['challenge'], ['sex'], ['abstinence'], ['come'], ['silver'], ['line'], ['join'], ['StoryBots'], ['space'], ['traveler'], ['historic'], ['inspiration4'], ['mission'], ['search'], ['answer'], ['kid'], ['question'], ['space'], ['jovial'], ['comic'], ['Jack'], ['Whitehall'], ['invite'], ['stuffy'], ['father'], ['Michael'], ['travel'], ['Southeast'], ['Asia'], ['attempt'], ['strengthen'], ['bond'], ['powerful'], ['businesswoman'], ['s'], ['political'], ['ambition'], ['threaten'], ['underworld'], ['connection'], ['ensue'], ['power'], ['struggle'], ['cost'], ['eye'], ['budget'], ['traveler'], ['visit'], ['vacation'], ['rental'], ['globe'], ['share'], ['expert'], ['tip'], ['trick'], ['reality'], ['series'], ['plane'], ['crash'], ['leave'], ['Bear'], ['amnesia'], ['choice'], ['save'], ['miss'], ['pilot'], ['survive'], ['high'], ['stake'], ['interactive'], ['adventure'], ['timid'], ['anime'], ['love'], ['teen'], ['get'], ['draw'], ['school'], ['cycling'], ['club'], ['new'], ['friend'], ['help'], ['face'], ['tough'], ['challenge'], ['develop'], ['racing'], ['talent'], ['kid'], ['cop'], ['Little'], ['Singham'], ['lose'], ['superpower'], ['try'], ['stop'], ['demon'], ['Kaal'], ['s'], ['new'], ['evil'], ['plan'], ['inner'], ['strength'], ['help'], ['defeat'], ['enemy'], ['bud'], ['politician'], ['devious'], ['plan'], ['rise'], ['rank'], ['unexpected'], ['new'], ['presence'], ['begin'], ['interfere'], ['crooked'], ['bud'], ['politician'], ['devious'], ['plan'], ['rise'], ['rank'], ['unexpected'], ['new'], ['presence'], ['begin'], ['interfere'], ['crooked'], ['home'], ['threaten'], ['human'], ['young'], ['dragon'], ['summon'], ['courage'], ['seek'], ['mythical'], ['paradise'], ['dragon'], ['live'], ['peace'], ['fly'], ['free'], ['slip'], ['fatal'], ['poison'], ['final'], ['job'], ['ruthless'], ['assassin'], ['work'], ['Tokyo'], ['hour'], ['find'], ['order'], ['hit'], ['exact'], ['revenge'], ['bore'], ['Lord'], ['Hell'], ['devil'], ['relocate'], ['Los'], ['Angeles'], ['open'], ['nightclub'], ['form'], ['connection'], ['homicide'], ['detective'], ['competition'], ['group'], ['metal'], ['artist'], ['torch'], ['cut'], ['weld'], ['epic'], ['badass'], ['creation'], ['hardened'], ['steel'], ['win'], ['prize'], ['twin'], ['reunite'], ['good'], ['hearted'], ['female'], ['gangster'], ['uptight'], ['rich'], ['sister'], ['family'], ['crime'], ['cop'], ['trouble'], ['follow'], ['Ash'], ['battle'], ['way'], ['World'], ['Coronation'], ['Series'], ['Goh'], ['continue'], ['quest'], ['catch'], ['Pokémon'], ['journey'], ['adventure'], ['hiking'], ['trip'], ['wild'], ['turn'], ['desperate'], ['bid'], ['survival'], ['friend'], ['run'], ['mysterious'], ['shooter'], ['titipo'], ['train'], ['prove'], ['s'], ['get'], ['take'], ['help'], ['folk'], ['Train'], ['Village'], ['ride'], ['rail'], ['safely'], ['reliably'], ['chance'], ['meeting'], ['tragic'], ['fallout'], ['Malcolm'], ['X'], ['Muhammad'], ['Ali'], ['s'], ['extraordinary'], ['bond'], ['crack'], ['weight'], ['distrust'], ['shift'], ['ideal'], ['bear'], ['superhuman'], ['ability'], ['young'], ['Raju'], ['want'], ['use'], ['power'], ['world'], ['well'], ['place'], ['mean'], ['face'], ['plenty'], ['challenge'], ['Uma'], ['wake'], ['lush'], ['tropical'], ['facility'], ['design'], ['turn'], ['willful'], ['girl'], ['perfect'], ['lady'], ['s'], ['bad'], ['real'], ['purpose'], ['bad'], ['documentary'], ['trace'], ['capture'], ['serial'], ['killer'], ['Guy'], ['Georges'], ['tireless'], ['work'], ['woman'], ['police'], ['chief'], ['victim'], ['s'], ['mother'], ['passenger'], ['crew'], ['aboard'], ['hijacked'], ['overnight'], ['flight'], ['scramble'], ['outrace'], ['sun'], ['mysterious'], ['cosmic'], ['event'], ['wreak'], ['havoc'], ['world'], ['Elisabeth'], ['John'], ['John'], ['live'], ['city'], ['inhabit'], ['different'], ['world'], ['passionate'], ['love'], ['break'], ['class'], ['cultural'], ['barrier'], ['rough'], ['tough'], ['police'], ['dog'], ['undercover'], ['FBI'], ['agent'], ['prim'], ['proper'], ['pet'], ['dog'], ['save'], ['baby'], ['panda'], ['illegal'], ['sale'], ['status'], ['strategy'], ['collide'], ['social'], ['experiment'], ['competition'], ['online'], ['player'], ['flirt'], ['befriend'], ['catfish'], ['way'], ['interview'], ['archival'], ['footage'], ['documentary'], ['chart'], ['story'], ['legendary'], ['Southern'], ['rocker'], ['focus'], ['man'], ['Ronnie'], ['Van'], ['Zant'], ['boy'], ['s'], ['superhero'], ['dream'], ['come'], ['true'], ['find'], ['powerful'], ['cosmic'], ['stone'], ['save'], ['day'], ['hard'], ['imagine'], ['t'], ['Octonauts'], ['expand'], ['exploration'], ['sea'], ['land'], ['new'], ['ride'], ['new'], ['friend'], ['ll'], ['protect'], ['habitat'], ['animal'], ['risk'], ['woman'], ['chef'], ['single'], ['mom'], ['heiress'], ['job'], ['seeker'], ['dig'], ['love'], ['work'], ['generous'], ['midlife'], ['crisis'], ['pre'], ['pandemic'], ['LA'], ['intergalactic'], ['device'], ['transform'], ['toy'], ['car'], ['robot'], ['Tobots'], ['work'], ['friend'], ['solve'], ['mystery'], ['protect'], ['world'], ['evil'], ['pressure'], ['continue'], ['win'], ['tradition'], ['american'], ['tennis'], ['mardy'], ['fish'], ['face'], ['mental'], ['health'], ['challenge'], ['change'], ['life'], ['court'], ['training'], ['launch'], ['land'], ['access'], ['docuserie'], ['rid'], ['inspiration4'], ['crew'], ['civilian'], ['orbital'], ['space'], ['mission'], ['family'], ['face'], ['destruction'], ['long'], ['run'], ['conflict'], ['community'], ['pit'], ['relative'], ['amid'], ['attack'], ['reprisal'], ['learn'], ['route'], ['busy'], ['city'], ['Tayo'], ['little'], ['bus'], ['friend'], ['discover'], ['new'], ['sight'], ['exciting'], ['adventure'], ['day'], ['grow'], ['amidst'], ['gang'], ['war'], ['hometown'], ['Vincent'], ['form'], ['entrepreneurial'], ['squad'], ['end'], ['wrong'], ['law'], ['Ross'], ['sibling'], ['Disney'], ['s'], ['hit'], ['series'], ['Jessie'], ['spend'], ['summer'], ['fun'], ['adventure'], ['Maine'], ['s'], ['Camp'], ['Kikiwaka'], ['parent'], ['meet'], ['grieve'], ['teen'], ['work'], ['debt'], ['ranch'], ['care'], ['wound'], ['horse'], ['teach'], ['healing'], ['expect'], ['shore'], ['Cape'], ['Mercy'], ['skillful'], ['group'], ['teen'], ['diver'], ['investigate'], ['series'], ['secret'], ['sign'], ['mysteriously'], ['go'], ['missing'], ['thief'], ['hostage'], ['lock'], ['Royal'], ['Mint'], ['Spain'], ['criminal'], ['mastermind'], ['manipulate'], ['police'], ['carry'], ['plan'], ['filmmaker'], ['actor'], ['Money'], ['heist'], ['character'], ['like'], ['Tokyo'], ['Professor'], ['talk'], ['emotional'], ['artistic'], ['process'], ['film'], ['series'], ['half'], ['shark'], ['half'], ['dog'], ['big'], ['heart'], ['belly'], ['fish'], ['stick'], ['Sharkdog'], ['human'], ['pal'], ['Max'], ['silly'], ['messy'], ['adventure'], ['wake'], ['Sept'], ['attack'], ['lawyer'], ['face'], ['emotional'], ['reckoning'], ['attempt'], ['dollar'], ['value'], ['life'], ['lose'], ['base'], ['real'], ['event'], ['cassie'], ['live'], ['party'], ['die'], ['freak'], ['accident'], ['social'], ['butterfly'], ['need'], ['right'], ['wrong'], ['Earth'], ['want'], ['earn'], ['wing'], ['wealthy'], ['industrialist'], ['s'], ['dangerous'], ['obsession'], ['flight'], ['attendant'], ['destroy'], ['world'], ['take'], ['matter'], ['hand'], ['exact'], ['revenge'], ['drama'], ['detail'], ['passionate'], ['year'], ['romance'], ['romantic'], ['poet'], ['John'], ['Keats'], ['die'], ['tragically'], ['age'], ['great'], ['love'], ['muse'], ['movie'], ['love'], ['year'], ['old'], ['blind'], ['little'], ['brother'], ['trek'], ['meet'], ['indian'], ['superstar'], ['Shah'], ['Rukh'], ['Khan'], ['help'], ['get'], ['boy'], ['eye'], ['operation'], ['documentary'], ['stitch'], ['see'], ['interview'], ['live'], ['generation'], ['people'], ['participate'], ['Hitler'], ['s'], ['Reich'], ['daughter'], ['wealthy'], ['family'], ['return'], ['college'], ['get'], ['frosty'], ['welcome'], ['brother'], ['problem'], ['plan'], ['meet'], ['heated'], 

In [ ]:
model=Word2Vec(data1,min_count=1,window=5,sg=0,epochs=10,vector_size=64)

In [ ]:
model.wv.get_vector('father')

array([-0.00414588, -0.01147169, -0.00557164, -0.00052596,  0.00952483,
       -0.00443334, -0.0001889 ,  0.00137457, -0.01108695,  0.00322657,
       -0.00223816,  0.00437836,  0.00756597, -0.00211253, -0.00434397,
        0.01209164,  0.00788375,  0.01048988,  0.00705569,  0.01354243,
        0.01167964, -0.00169045,  0.01366819,  0.00719018,  0.00850099,
       -0.00216576, -0.00318956, -0.00691304, -0.013305  ,  0.00474645,
        0.01387999,  0.0139371 , -0.00303493,  0.00950962,  0.00590582,
       -0.00671245,  0.00319207, -0.0084967 ,  0.01282639,  0.00848892,
        0.00497568,  0.00641026,  0.0135268 ,  0.01136255, -0.0013023 ,
       -0.0110512 ,  0.01309449,  0.01130247,  0.00270386, -0.00210546,
       -0.00920327, -0.00708295,  0.01351245, -0.00489861, -0.00990441,
        0.015422  ,  0.01202601,  0.014251  ,  0.00177422, -0.01300794,
        0.01316409, -0.00577536,  0.00897215,  0.00686184], dtype=float32)

In [ ]:
model.wv.get_vector('father').shape

(64,)

In [ ]:
model.wv.most_similar('man')

[('favorite', 0.46087273955345154),
 ('Snyder', 0.42879775166511536),
 ('Pine', 0.42569786310195923),
 ('godly', 0.4226153790950775),
 ('Audrey', 0.420467734336853),
 ('tidbit', 0.412655234336853),
 ('thrilling', 0.4111185669898987),
 ('fledged', 0.40247842669487),
 ('infiltrate', 0.4013824164867401),
 ('LeRoy', 0.40034589171409607)]

Pre-Trained-Model

In [ ]:
gensim.downloader.info()['models'].keys()

dict_keys(['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis'])

In [ ]:
model1=gensim.downloader.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [ ]:
model1.get_vector('father')

array([ 0.04736328, -0.03173828,  0.04077148, -0.15332031,  0.07421875,
        0.06054688, -0.02526855, -0.20898438,  0.12792969,  0.00488281,
        0.4375    , -0.29492188, -0.05297852, -0.14648438, -0.3515625 ,
        0.05834961, -0.07714844,  0.21484375, -0.00270081,  0.09375   ,
       -0.06396484,  0.17675781,  0.14550781,  0.11279297,  0.14453125,
       -0.22167969, -0.12402344,  0.04663086,  0.12451172, -0.14453125,
        0.24609375, -0.06396484, -0.17773438,  0.21875   ,  0.07861328,
        0.19921875,  0.3125    , -0.06738281,  0.08740234,  0.00411987,
        0.25      , -0.1171875 ,  0.21875   , -0.15625   ,  0.22363281,
        0.11230469, -0.1640625 ,  0.04003906,  0.02722168, -0.22949219,
       -0.01879883,  0.09863281,  0.0213623 , -0.17089844,  0.18457031,
       -0.10449219, -0.28710938,  0.04174805, -0.16601562, -0.06298828,
        0.18847656,  0.07421875,  0.09521484,  0.01184082,  0.11181641,
        0.15039062, -0.01953125, -0.01586914,  0.08935547, -0.05029297,
        0.11279297,  0.02111816, -0.19824219,  0.19042969, -0.24609375,
        0.26367188,  0.06933594, -0.08496094,  0.23144531,  0.06445312,
        0.2734375 ,  0.09472656, -0.13574219, -0.14550781, -0.07080078,
       -0.01226807, -0.08007812,  0.08154297, -0.16308594, -0.01574707,
       -0.18164062, -0.05761719, -0.20898438, -0.06396484, -0.00866699,
       -0.09423828,  0.07275391,  0.03637695,  0.07763672, -0.10546875,
       -0.13867188, -0.10986328,  0.1328125 , -0.17578125, -0.12255859,
       -0.06445312,  0.02282715,  0.08056641,  0.14355469,  0.20800781,
        0.05297852,  0.07568359,  0.05200195, -0.12011719,  0.12402344,
       -0.09765625, -0.17578125, -0.10839844,  0.13867188,  0.10400391,
       -0.05786133,  0.09521484,  0.07373047, -0.09960938, -0.13183594,
       -0.06079102,  0.10302734, -0.06396484,  0.00087357,  0.05517578,
       -0.04077148, -0.07861328, -0.06640625, -0.0390625 ,  0.06103516,
        0.0703125 ,  0.05322266,  0.16015625,  0.08300781,  0.13769531,
        0.09814453,  0.05761719, -0.11083984, -0.04541016, -0.00408936,
        0.12597656, -0.2265625 ,  0.0480957 , -0.10791016,  0.03710938,
        0.328125  ,  0.13476562, -0.06005859,  0.109375  , -0.09033203,
        0.19628906, -0.03930664, -0.09667969,  0.24316406, -0.19726562,
       -0.01220703,  0.10009766,  0.13574219,  0.19140625,  0.00769043,
       -0.11865234,  0.265625  ,  0.04711914,  0.13476562,  0.24609375,
        0.25195312, -0.01483154,  0.03759766, -0.31054688, -0.02770996,
        0.05102539,  0.32226562,  0.13183594,  0.01019287,  0.10449219,
       -0.06884766, -0.00982666,  0.0703125 ,  0.08984375,  0.09179688,
        0.11816406,  0.18457031,  0.23046875,  0.08984375,  0.22363281,
       -0.07861328,  0.30078125, -0.05761719,  0.10351562,  0.15136719,
        0.15527344, -0.10107422, -0.11767578, -0.05200195,  0.11572266,
       -0.328125  , -0.05102539, -0.13671875, -0.14257812,  0.3359375 ,
       -0.01513672,  0.00247192, -0.06201172, -0.03710938, -0.31054688,
       -0.0480957 , -0.03466797,  0.10888672,  0.0072937 , -0.07470703,
        0.02661133, -0.0703125 ,  0.19335938, -0.10546875, -0.1328125 ,
        0.04833984, -0.03710938,  0.33398438, -0.08203125,  0.12402344,
       -0.20507812,  0.05761719, -0.03515625, -0.13671875, -0.09814453,
        0.08837891, -0.00897217, -0.08447266,  0.06494141,  0.04492188,
       -0.04589844, -0.125     , -0.20605469, -0.1875    ,  0.03491211,
       -0.22753906, -0.22265625, -0.17382812,  0.06298828,  0.04321289,
        0.3203125 , -0.07958984,  0.07128906,  0.16308594, -0.15332031,
        0.23339844,  0.04174805,  0.12109375, -0.125     ,  0.13671875,
        0.00265503, -0.04248047, -0.03466797, -0.3203125 , -0.02648926,
        0.21972656, -0.04077148,  0.11572266, -0.08740234,  0.09619141,
        0.22753906, -0.11767578, -0.11328125, -0.05151367,  0.21289062,
        0.01782227, -0.12011719,  0.06396484,  0.11132812,  0.07666016,
       -0.12988281, -0.00765991,  0.06835938,  0.03857422, -0.15234375,
        0.20019531, -0.20410156,  0.10546875,  0.22460938, -0.08154297,
        0.13476562, -0.20117188,  0.19433594, -0.11962891,  0.28515625,
       -0.22460938, -0.04101562, -0.23339844, -0.24902344,  0.05175781,
       -0.04003906, -0.26171875, -0.24414062,  0.02929688,  0.08837891],
      dtype=float32)

In [ ]:
model1.get_vector('father').shape

(300,)

In [ ]:
model1.most_similar('mother')

[('daughter', 0.8706234097480774),
 ('grandmother', 0.8442240953445435),
 ('aunt', 0.843592643737793),
 ('niece', 0.807008683681488),
 ('father', 0.7901482582092285),
 ('son', 0.7683205604553223),
 ('sister', 0.7633354067802429),
 ('wife', 0.7550681233406067),
 ('stepmother', 0.7531880140304565),
 ('granddaughter', 0.7470966577529907)]

In [ ]:
vec1=model1['mother']+model1['father']

In [ ]:
model1.most_similar([vec1])

[('mother', 0.9475696682929993),
 ('father', 0.9445772171020508),
 ('son', 0.8772615790367126),
 ('daughter', 0.8508231043815613),
 ('grandmother', 0.8130332827568054),
 ('aunt', 0.8079724311828613),
 ('uncle', 0.8024557828903198),
 ('stepfather', 0.8012963533401489),
 ('husband', 0.7833577990531921),
 ('niece', 0.7803018689155579)]

In [ ]:
model1.most_similar('india')

[('indian', 0.6967039704322815),
 ('usa', 0.6836211085319519),
 ('pakistan', 0.681516706943512),
 ('chennai', 0.6675503253936768),
 ('america', 0.6589399576187134),
 ('sri_lanka', 0.64982008934021),
 ('canada', 0.6490967869758606),
 ('australia', 0.6368584036827087),
 ('mexico', 0.6239137649536133),
 ('uk', 0.6221641898155212)]

In [ ]:
model1.most_similar('sachin')

[('tendulkar', 0.7856917381286621),
 ('ganguly', 0.7785738706588745),
 ('sehwag', 0.7773319482803345),
 ('dravid', 0.7691141366958618),
 ('sachin_tendulkar', 0.741614580154419),
 ('laxman', 0.7271499037742615),
 ('KrisSrikkanth_says', 0.6995106339454651),
 ('murali', 0.6993196606636047),
 ('afridi', 0.6891643404960632),
 ('odi', 0.6883801817893982)]

In [ ]:
model1.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [ ]:
model1.most_similar('putin')

[('syria', 0.6041068434715271),
 ('russians', 0.5952029824256897),
 ('distroy', 0.5681545734405518),
 ('kosovo', 0.567267119884491),
 ('sarkozy', 0.5630715489387512),
 ('kurds', 0.5621310472488403),
 ('manmohan', 0.5572597980499268),
 ('serbs', 0.5456642508506775),
 ("Ah'm", 0.5440203547477722),
 ('mugabe', 0.5429834723472595)]

In [ ]:
model1.most_similar('trump')

[('trumps', 0.7198434472084045),
 ('trumping', 0.580585241317749),
 ('supersede', 0.5600422620773315),
 ('trumped', 0.5497318506240845),
 ('supercede', 0.5309919118881226),
 ('prevail', 0.487763375043869),
 ('outweigh', 0.47853273153305054),
 ('trample', 0.4714253544807434),
 ('overshadow', 0.4701153635978699),
 ('dictate', 0.46754559874534607)]